FROM microprofile/server:1.0.0

ADD portfolio-app/target/portfolio-app.war /opt/portfolio-app.war
ADD portfolio-app/src/main/filters/project-defaults.yml /opt/project-defaults.yml

EXPOSE 8080

ENTRYPOINT ["java", "-Xmx64m", "-jar", "/opt/hollow-thorntail.jar", "-Djava.net.preferIPv4Stack=true", "/opt/portfolio-app.war", "-s", "/opt/project-defaults.yml"]